services:
  service:
    image: ghcr.io/sebastian-struecker/simple-feature-toggles/service:1.0.0-snapshot
    environment:
      DATASOURCE_DATABASE: service
      DATASOURCE_USERNAME: service
      DATASOURCE_PASSWORD: service
      DATASOURCE_HOST: service_database
      DATASOURCE_PORT: 5432
      OIDC_AUTH_SERVER_URL: http://host.docker.internal:8000/realms/simple-feature-toggles
      OIDC_CLIENT_ID: simple-feature-toggles
      OIDC_TOKEN_JWT_ISSUER: http://localhost:8000/realms/simple-feature-toggles
      OIDC_TOKEN_JWT_AUDIENCE: simple-feature-toggles
      API_KEYS: test
    ports:
      - 8080:8080

  service_database:
    image: bitnami/postgresql:16.3.0
    environment:
      POSTGRESQL_USERNAME: service
      POSTGRESQL_PASSWORD: service
      POSTGRESQL_DATABASE: service
    ports:
      - 5432:5432

  keycloak:
    image: bitnami/keycloak:24.0.5
    environment:
      KEYCLOAK_HTTP_PORT: 8000
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KEYCLOAK_DATABASE_HOST: keycloak_database
      KEYCLOAK_DATABASE_PORT: 5000
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
      KEYCLOAK_EXTRA_ARGS: --import-realm
    volumes:
      - './src/main/resources:/opt/bitnami/keycloak/data/import'
    depends_on:
      - keycloak_database
    ports:
      - 8000:8000

  keycloak_database:
    image: bitnami/postgresql:16.3.0
    environment:
      POSTGRESQL_USERNAME: keycloak
      POSTGRESQL_PASSWORD: keycloak
      POSTGRESQL_DATABASE: keycloak
      POSTGRESQL_PORT_NUMBER: 5000
