quarkus:
  datasource:
    db-kind: postgresql

  smallrye-openapi:
    path: /openapi
    store-schema-directory: target

  swagger-ui:
    always-include: true
    path: /swagger-ui

  http:
    cors:
      ~: true
      origins: /.*/
      headers: origin, host, referer, accept, accept-encoding, accept-language, authorization, content-type, x-api-key
      access-control-allow-credentials: true
      methods: GET,PUT,POST,PATCH,DELETE

  tls:
    trust-all: true

api:
  authorization:
    enable: ${API_AUTHORIZATION_ENABLE:true}

"%prod":
  quarkus:
    datasource:
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      reactive:
        url: vertx-reactive:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
    hibernate-orm:
      database:
        generation:
          ~: update
          create-schemas: true

    oidc:
      auth-server-url: ${OIDC_AUTH_SERVER_URL}
      client-id: ${OIDC_CLIENT_ID}
      token:
        issuer: ${OIDC_TOKEN_JWT_ISSUER}
        audience: ${OIDC_TOKEN_JWT_AUDIENCE}

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        port: 5432
        username: sft
        password: sft
    hibernate-orm:
      database:
        generation: drop-and-create

    keycloak:
      devservices:
        enabled: false

  smallrye-openapi:
    ~: false
    enable: false

  swagger-ui:
    ~: false
    enable: false

  api:
    authorization:
      enable: true

"%dev":
  quarkus:
    log:
      level:
        category:
          "simple_feature_toggles":
            level: DEBUG

    datasource:
      devservices:
        enabled: true
        port: 5432
        username: sft
        password: sft
    hibernate-orm:
      database:
        generation: drop-and-create

    oidc:
      client-id: simple-feature-toggles
      token:
        issuer: http://localhost:8000/realms/simple-feature-toggles
        audience: simple-feature-toggles

    keycloak:
      devservices:
        enabled: true
        port: 8000
        realm-name: simple-feature-toggles
        realm-path: example-keycloak-settings.json

  api:
    authorization:
      enable: false
