quarkus:
  datasource:
    db-kind: postgresql

  # Switch with hibernate-orm when Intellij IDEA v2024.3.2
  #  flyway:
  #    locations: db/migration
  #    migrate-at-start: true

  hibernate-orm:
    database:
      generation:
        ~: update
        create-schemas: true

  smallrye-openapi:
    path: /openapi
    store-schema-directory: target

  swagger-ui:
    always-include: true
    path: /swagger-ui

  http:
    cors:
      ~: true
      origins: /.*/
      headers: origin, host, referer, accept, accept-encoding, accept-language, authorization, content-type, x-api-key
      access-control-allow-credentials: true
      methods: GET,PUT,POST,PATCH,DELETE

  tls:
    trust-all: true

  api:
    authorization:
      enabled: ${API_AUTHORIZATION_ENABLED:true}

"%prod":
  quarkus:
    datasource:
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      reactive:
        url: vertx-reactive:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
      jdbc:
        url: postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}

    oidc:
      auth-server-url: ${OIDC_AUTH_SERVER_URL}
      client-id: ${OIDC_CLIENT_ID}
      token:
        issuer: ${OIDC_TOKEN_JWT_ISSUER}
        audience: ${OIDC_TOKEN_JWT_AUDIENCE}

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        port: 5432
        db-name: sft
        username: sft
        password: sft

    keycloak:
      devservices:
        enabled: false

  smallrye-openapi:
    ~: false
    enable: false

  swagger-ui:
    ~: false
    enable: false

"%dev":
  quarkus:
    log:
      category:
        "simple_feature_toggles":
          level: DEBUG

    datasource:
      devservices:
        enabled: true
        port: 5432
        db-name: sft
        username: sft
        password: sft

    oidc:
      client-id: simple-feature-toggles
      token:
        issuer: http://localhost:8000/realms/simple-feature-toggles
        audience: simple-feature-toggles

    keycloak:
      devservices:
        enabled: true
        port: 8000
        realm-name: simple-feature-toggles
        realm-path: example-keycloak-settings.json
