name: Build Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven Package
        run: ./mvnw -B package -DskipTests

      - name: Docker log in to Github Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from pom.xml file
        id: project
        uses: dostonhamrakulov/maven-artifact-version-extractor@v1.0
        with:
          file_path: ${{ github.workspace }}/pom.xml

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd
        with:
          context: .
          file: ./src/main/docker/Dockerfile
          push: true
          tags: ghcr.io/sebastian-struecker/simple-feature-toggles:${{ steps.project.outputs.version }}

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from pom.xml file
        id: project
        uses: dostonhamrakulov/maven-artifact-version-extractor@v1.0
        with:
          file_path: ${{ github.workspace }}/pom.xml

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/sebastian-struecker/simple-feature-toggles:${{ steps.project.outputs.version }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
