name: Ui - Build Image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/ui-build-image.yml'
      - 'ui/**'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v4

        - name: get-npm-version
          id: package-version
          uses: martinbeentjes/npm-get-version-action@v1.3.1

        - name: Build and push Docker images
          id: push
          uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd
          with:
            context: .
            file: ./ui/Dockerfile
            push: true
            tags: ghcr.io/sebastian-struecker/simple-feature-toggles/ui:${{ steps.package-version.outputs.current-version }}

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/sebastian-struecker/simple-feature-toggles/ui:${{ steps.package-version.outputs.current-version }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
